# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_build_skeleton <- function(data, max_d) {
    .Call(`_aRchi_cpp_build_skeleton`, data, max_d)
}

cpp_compute_layers <- function(coords, D) {
    .Call(`_aRchi_cpp_compute_layers`, coords, D)
}

cpp_compute_topology <- function(skel) {
    .Call(`_aRchi_cpp_compute_topology`, skel)
}

cpp_smooth_skeleton <- function(qsm, niter = 1L, th = 0) {
    .Call(`_aRchi_cpp_smooth_skeleton`, qsm, niter, th)
}

